# Overrides the docker-compose file for production environment
# - Adds nginx with basic auth in front of the app

version: '3'

volumes:
  letsencrypt:

services:

  app:
    volumes:
      - /mnt/ngdr/:/mnt/ngdr

  nginx:
    build: docker/nginx
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd:ro
    env_file:
      - .env
    command: "sed -i 's%X.X.X.0/24%${NGINX_NIMS_IP_RANGE}%g' /etc/nginx.conf && nginx -s reload"
    ports:
      - 80:80
      - 443:443
    networks:
      internal:
