terms:
  - id: Article
    term: Article
  - id: Audio
    term: Audio
  - id: Book
    term: Book
  - id: Conference Proceeding
    term: Conference Proceeding
  - id: Dissertation
    term: Dissertation
  - id: Image
    term: Image
  - id: Poster
    term: Poster
  - id: Presentation
    term: Presentation
  - id: Report
    term: Report
  - id: Video
    term: Video
  - id: Other
    term: Other
