development:
  fluent_host:   'fluentd'
  fluent_port:   24224
  tag:           'mdr'
  messages_type: 'string'

test:
  fluent_host:   'fluentd'
  fluent_port:   24224
  tag:           'mdr'
  messages_type: 'string'

production:
  fluent_host:   'fluentd'
  fluent_port:   24224
  tag:           'mdr'
  messages_type: 'string'
